-- unit sounds

  nothing =
	{
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
	},

  gbryard =
	{
	--select1="gbr_anthem",
	unitcomplete="gen_yarddone",
	underattack="",
	build="gen_yardselect",
	working="",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
	},

  geryard =
	{
	--select1="ger_anthem",
	unitcomplete="gen_yarddone",
	underattack="",
	build="gen_yardselect",
	working="",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
	},

  rusyard =
	{
	--select1="rus_anthem",
	unitcomplete="gen_yarddone",
	underattack="",
	build="gen_yardselect",
	working="",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
	},

  usyard =
	{
	--select1="us_anthem",
	unitcomplete="gen_yarddone",
	underattack="",
	build="gen_yardselect",
	working="",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
	},

  usinf =
	{
	select1="us_inf_select1",
	select2="us_inf_select2",
	select3="us_inf_select3",
	ok1="us_inf_ok1",
	ok2="us_inf_ok2",
	ok3="us_inf_ok3",
	--arrived1="us_inf_arrived1",
	--arrived2="us_inf_arrived2",
	--arrived3="us_inf_arrived3",
	underattack="us_inf_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  ustank =
	{
	select1="us_tank_select1",
	select2="us_tank_select2",
	select3="us_tank_select3",
	ok1="us_tank_ok1",
	ok2="us_tank_ok2",
	ok3="us_tank_ok3",
	arrived1="us_tank_arrived1",
	arrived2="us_tank_arrived2",
	--arrived3="us_tank_arrived3",
	underattack="us_tank_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  usveh =
	{
	select1="us_veh_select1",
	select2="us_veh_select2",
	select3="us_veh_select3",
	ok1="us_veh_ok1",
	ok2="us_veh_ok2",
	ok3="us_veh_ok3",
	arrived1="us_veh_arrived",
	underattack="us_veh_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  usgun =--meh, incomplete, unclean, Joy Joy
	{
	select1="us_veh_select1",
	select2="us_veh_select2",
	select3="us_veh_select3",
	ok1="us_gun_ok1",
	ok2="us_gun_ok2",
	cant1="us_gun_withdraw",
	arrived1="us_gun_deploy",
	arrived2="us_gun_ok3",
	underattack="us_gun_underattack",
	--deploy="us_gun_deploy", --can we call sfx in morphs through sounds.tdf?
	--stop="us_gun_stop",
	--withdraw="us_gun_withdraw",
		},

  rusinf =
	{
	select1="rus_inf_select1",
	select2="rus_inf_select2",
	select3="rus_inf_select3",
	ok1="rus_inf_ok1",
	ok2="rus_inf_ok2",
	ok3="rus_inf_ok3",
	--cant1="rus_inf_cant",
	--arrived1="rus_inf_arrived1",
	--arrived2="rus_inf_arrived2",
	--arrived3="rus_inf_arrived3",
	underattack="rus_inf_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  russniper =
	{
	select1="rus_sniper_select1",
	select2="rus_sniper_select2",
	select3="rus_sniper_select3",
	ok1="rus_sniper_ok1",
	ok2="rus_sniper_ok2",
	ok3="rus_sniper_ok3",
	ok4="rus_sniper_ok4",
	cant1="rus_sniper_cant",
	--arrived1="rus_inf_arrived1",
	--arrived2="rus_inf_arrived2",
	--arrived3="rus_inf_arrived3",
	underattack="rus_sniper_underattack1",
	underattack2="rus_sniper_underattack2",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  rusgun =
	{
	select1="rus_arty_select1",
	select2="rus_arty_select2",
	select3="rus_arty_select3",
	select3="rus_arty_select4",
	ok1="rus_arty_ok1",
	ok2="rus_arty_ok2",
	ok3="rus_arty_ok3",
	ok3="rus_arty_ok4",
	cant1="rus_arty_cant",
	--arrived1="rus_inf_arrived1",
	--arrived2="rus_inf_arrived2",
	--arrived3="rus_inf_arrived3",
	underattack="rus_arty_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  rustank =
	{
	select1="rus_tank_select1",
	select2="rus_tank_select2",
	select3="rus_tank_select3",
	ok1="rus_tank_ok1",
	ok2="rus_tank_ok2",
	ok3="rus_tank_ok3",
	cant1="rus_tank_cant",
	arrived1="rus_tank_arrived1",
	arrived2="rus_tank_arrived2",
	arrived3="rus_tank_arrived3",
	underattack="rus_tank_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  rusboat =
	{
	select1="rus_boat_select1",
	select2="rus_boat_select2",
	select3="rus_boat_select3",
	ok1="rus_boat_ok1",
	ok2="rus_boat_ok2",
	ok3="rus_boat_ok3",
	cant1="rus_boat_cant",
	arrived1="rus_boat_arrived1",
	arrived2="rus_boat_arrived2",
	arrived3="rus_boat_arrived3",
	underattack="rus_boat_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  ruszveroboy =
	{
	select1="rus_zveroboy_select1",
	select2="rus_zveroboy_select2",
	select3="rus_zveroboy_select3",
	select4="rus_zveroboy_select4",
	ok1="rus_zveroboy_ok1",
	ok2="rus_zveroboy_ok2",
	ok3="rus_zveroboy_ok3",
	cant1="rus_zveroboy_cant",
	arrived1="rus_zveroboy_arrived1",
	arrived2="rus_zveroboy_arrived2",
	arrived3="rus_zveroboy_arrived3",
	underattack="rus_zveroboy_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  rusveh =
	{
	select1="rus_veh_select1",
	select2="rus_veh_select2",
	ok1="rus_veh_ok1",
	ok2="rus_veh_ok2",
	cant="rus_veh_cant",
	arrived1="rus_veh_arrived1",
	arrived2="rus_veh_arrived2",
	underattack="rus_veh_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	},

  ruspo2 =
	{
	select1="rus_air_po2_select",
	ok1="rus_air_ok1",
	ok2="rus_air_ok2",
	ok3="rus_air_ok3",
	ok4="rus_air_ok4",
	ok5="rus_air_ok5",
	ok6="rus_air_ok6",
	ok7="rus_air_ok7",
	ok8="rus_air_ok8",
	ok9="rus_air_ok9",
	cant="rus_air_cant",
	underattack="rus_air_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	},

  rusil2 =
	{
	select1="rus_air_il2_select",
	ok1="rus_air_il2_ok",
	ok2="rus_air_ok2",
	ok3="rus_air_ok3",
	ok4="rus_air_ok4",
	ok5="rus_air_ok5",
	ok6="rus_air_ok6",
	ok7="rus_air_ok7",
	ok8="rus_air_ok8",
	ok9="rus_air_ok9",
	cant="rus_air_cant",
	underattack="rus_air_underaafire",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	},

  rusfighter =
	{
	select1="rus_air_fighter_select",
	ok1="rus_air_ok1",
	ok2="rus_air_ok2",
	ok3="rus_air_ok3",
	ok4="rus_air_ok4",
	ok5="rus_air_ok5",
	ok6="rus_air_ok6",
	ok7="rus_air_ok7",
	ok8="rus_air_ok8",
	ok9="rus_air_ok9",
	cant="rus_air_cant",
	underattack="rus_air_imgoingdown!",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	},

  gbrinf =
	{
	select1="gbr_inf_select1",
	select2="gbr_inf_select2",
	select3="gbr_inf_select3",
	ok1="gbr_inf_ok1",
	ok2="gbr_inf_ok2",
	ok3="gbr_inf_ok3",
	--cant1="gbr_inf_cant",
	underattack="gbr_inf_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gbrtank =
	{
	select1="gbr_tank_select1",
	select2="gbr_tank_select2",
	select3="gbr_tank_select3",
	ok1="gbr_tank_ok1",
	ok2="gbr_tank_ok2",
	ok3="gbr_tank_ok3",
	cant1="gbr_tank_cant",
	arrived1="gbr_tank_arrived1",
	arrived2="gbr_tank_arrived2",
	underattack="gbr_tank_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gbrsp =
	{
	select1="gbr_sp_select1",
	select2="gbr_tank_select2",
	select3="gbr_tank_select3",
	ok1="gbr_sp_ok1",
	ok2="gbr_tank_ok2",
	ok3="gbr_tank_ok3",
	cant1="gbr_tank_cant",
	arrived1="gbr_tank_arrived1",
	arrived2="gbr_tank_arrived2",
	underattack="gbr_tank_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gbrchurchill =
	{
	select1="gbr_churchill_select1",
	select2="gbr_tank_select2",
	select3="gbr_tank_select3",
	ok1="gbr_churchill_ok1",
	ok2="gbr_tank_ok2",
	ok3="gbr_tank_ok3",
	cant1="gbr_tank_cant",
	arrived1="gbr_tank_arrived1",
	arrived2="gbr_tank_arrived2",
	underattack="gbr_tank_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gbrveh =
	{
	select1="gbr_vehicle_select1",
	select2="gbr_vehicle_select2",
	select3="gbr_vehicle_select3",
	ok1="gbr_vehicle_ok1",
	ok2="gbr_vehicle_ok2",
	ok3="gbr_vehicle_ok3",
	--cant1="gbr_vehicle_cant",
	arrived1="gbr_vehicle_arrived1",
	--arrived2="gbr_vehicle_arrived2",
	underattack="gbr_vehicle_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gerinf =
	{
	select1="ger_inf_select1",
	select2="ger_inf_select2",
	select3="ger_inf_select3",
	ok1="ger_inf_ok1",
	ok2="ger_inf_ok2",
	ok3="ger_inf_ok3",
	--cant1="",
	underattack="ger_inf_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gertank =
	{
	select1="ger_tank_select1",
	--select2="ger_tank_select2",
	--select3="ger_tank_select3",
	ok1="ger_tank_ok1",
	--ok2="ger_tank_ok2",
	--ok3="ger_tank_ok3",
	--cant1="ger_tank_cant",
	arrived1="ger_tank_arrived1",
	arrived2="ger_tank_arrived2",
	underattack="ger_tank_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  cdninf =
	{
	select1="cdn_inf_select1",
	select2="cdn_inf_select2",
	select3="cdn_inf_select3",
	ok1="cdn_inf_ok1",
	ok2="cdn_inf_ok2",
	ok3="cdn_inf_ok3",
	--arrived1="us_inf_arrived1",
	--arrived2="us_inf_arrived2",
	--arrived3="us_inf_arrived3",
	underattack="cdn_inf_underattack",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gerstug =
	{
	select1="ger_armor_select1",
	--select2="ger_tank_select2",
	--select3="ger_tank_select3",
	ok1="ger_stug_ok1",
	--ok2="ger_tank_ok2",
	--ok3="ger_tank_ok3",
	--cant1="ger_tank_cant",
	arrived1="ger_stug_arrived1",
	arrived2="ger_tanknew_arrived4",
	underattack="ger_underattack_new",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gertanknew =
	{
	select1="ger_armor_select1",
	--select2="ger_tank_select2",
	--select3="ger_tank_select3",
	ok1="ger_tanknew_ok1",
	ok2="ger_tanknew_ok2",
	ok3="ger_tanknew_ok3",
	--cant1="ger_tank_cant",
	arrived1="ger_tanknew_arrived1",
	arrived2="ger_tanknew_arrived2",
	arrived3="ger_tanknew_arrived3",
	arrived4="ger_tanknew_arrived4",
	underattack="ger_underattack_new",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gerJgpz =
	{
	select1="ger_armor_select1",
	--select2="ger_tank_select2",
	--select3="ger_tank_select3",
	ok1="ger_Jgpz_ok1",
	--ok2="ger_tank_ok2",
	--ok3="ger_tank_ok3",
	--cant1="ger_tank_cant",
	arrived1="ger_Jgpz_arrived1",
	arrived2="ger_tanknew_arrived4",
	underattack="ger_underattack_new",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gerfaust =
	{
	select1="ger_infnew_select1",
--	select2="ger_inf_select2",
--	select3="ger_inf_select3",
	ok1="ger_faust_ok1",
	ok2="ger_inf_ok4",
	--cant1="",
	underattack="ger_underattack_new",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	}, 

  gersniper =
	{
	select1="ger_infnew_select1",
--	select2="ger_inf_select2",
--	select3="ger_inf_select3",
	ok1="ger_sniper_ok1",
	ok2="ger_inf_ok4",
	--cant1="",
	underattack="ger_underattack_new",
	count5="gen_alarm",
	count4="gen_alarm",
	count3="gen_alarm",
	count2="gen_alarm",
	count1="gen_alarm",
	count0="gen_alarm",
	canceldestruct="",
      	} 
