-- dirtexpl

return {
  ["dirtexpl"] = {
    glow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0.01   1 1 0.8 0.9              0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[-0, 1, 0]],
        gravity            = [[0, 0.00, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 0,
        particlesize       = 60,
        particlesizespread = 10,
        particlespeed      = 1,
        particlespeedspread = 0,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0,
        sizemod            = 0.8,
        texture            = [[diamondstar]],
      },
    },
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 8,
      flashalpha         = 0.9,
      flashsize          = 25,
      ttl                = 8,
      color = {
        [1]  = 0.80000001192093,
        [2]  = 0.80000001192093,
        [3]  = 0.80000001192093,
      },
    },
    particlesystem_dust1 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 15,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.98,
        colormap           = [[.2 .2 .2 1  0 0 0 .3   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 50,
        emitvector         = [[0, 1, 0]],
        gravity            = [[-.025 r.05,  -.35,  -.025 r.05]],
        numparticles       = 1,
        particlelife       = 40,
        particlelifespread = 20,
        particlesize       = 15,
        particlesizespread = 5,
        particlespeed      = 2,
        particlespeedspread = 7,
        pos                = [[-10 r20, 5 r10, -10 r20]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[dust2]],
      },
    },
    particlesystem_dust2 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 15,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.98,
        colormap           = [[.2 .2 .2 1  0 0 0 .3   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 35,
        emitvector         = [[0, 1, 0]],
        gravity            = [[-.025 r.05,  -.35,  -.025 r.05]],
        numparticles       = 1,
        particlelife       = 25,
        particlelifespread = 20,
        particlesize       = 15,
        particlesizespread = 5,
        particlespeed      = 2,
        particlespeedspread = 7,
        pos                = [[-10 r20, 5 r10, -10 r20]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
    particlesystem_dust3 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 15,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.98,
        colormap           = [[.2 .2 .2 1  0 0 0 .3   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -.35, 0]],
        numparticles       = 1,
        particlelife       = 50,
        particlelifespread = 20,
        particlesize       = 15,
        particlesizespread = 5,
        particlespeed      = 3,
        particlespeedspread = 12,
        pos                = [[-10 r20, 5 r10, -10 r20]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 0,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        alwaysvisible      = true,
        colormap           = [[1 1 0 0.01   1 0.7 0.5 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.4, 0]],
        numparticles       = 20,
        particlelife       = 30,
        particlelifespread = 0,
        particlesize       = 2,
        particlesizespread = 7,
        particlespeed      = 2,
        particlespeedspread = 16,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 0.8,
        texture            = [[plasma]],
      },
    },
  },

}

