-- he_medium

return {
  ["he_medium"] = {
    usedefaultexplosions = false,
    airheat = {
      air                = true,
      class              = [[CHeatCloudProjectile]],
      count              = 4,
      properties = {
        heat               = 8,
        heatfalloff        = 1,
        maxheat            = 16,
        pos                = [[-4 r8, -4 r8, -4 r8]],
        size               = 1,
        sizegrowth         = 4,
        texture            = [[heatcloud]],
      },
    },
    airsmoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      properties = {
        airdrag            = 0.75,
        alwaysvisible      = false,
        colormap           = [[0.125 0.125 0.125 1  0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 96,
        particlelifespread = 64,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0.5,
        particlespeedspread = 0.25,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[4 r4]],
        sizemod            = 0.875,
        texture            = [[smokesmall]],
      },
    },
    dirt = {
      class              = [[CDirtProjectile]],
      count              = 8,
      ground             = true,
      properties = {
        alpha              = 255,
        alphafalloff       = 10,
        color              = [[0.4 r0.1, 0.3 r0.1, 0.2 r0.1]],
        pos                = [[-2 r4, r2, -2 r4]],
        size               = [[8 r16]],
        sizeexpansion      = 0,
        slowdown           = 0.95,
        speed              = [[-2 r4, r2, -2 r4]],
        texture            = [[randdots]],
      },
    },
    dust = {
      class              = [[CBitmapMuzzleFlame]],
      count              = 8,
      ground             = true,
      properties = {
        colormap           = [[0.5 0.4 0.3 1  0.05 0.04 0.03 0.1]],
        dir                = [[-0.1 r0.2, 1, -0.1 r0.2]],
        frontoffset        = 0,
        fronttexture       = [[splashbase]],
        length             = [[16 r16]],
        sidetexture        = [[splashside]],
        size               = [[8 r4]],
        sizegrowth         = 1,
        ttl                = 24,
      },
    },
    groundflash = {
      circlealpha        = 0,
      circlegrowth       = 10,
      flashalpha         = 1,
      flashsize          = 32,
      ttl                = 8,
      color = {
        [1]  = 1,
        [2]  = 0.75,
        [3]  = 0.5,
      },
    },
    smoke = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.75,
        alwaysvisible      = false,
        colormap           = [[0.5 0.5 0.5 1  0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 8,
        particlelife       = 24,
        particlelifespread = 8,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[4 r4]],
        sizemod            = 0.5,
        texture            = [[smokesmall]],
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.125,
        color              = [[1,1,1]],
        expansionspeed     = 4,
        ttl                = 8,
      },
    },
    water = {
      class              = [[CBitmapMuzzleFlame]],
      count              = 8,
      water              = true,
      properties = {
        colormap           = [[0.45 0.45 0.5 0.5  0.045 0.045 0.05 0.05]],
        dir                = [[-0.1 r0.2, 1, -0.1 r0.2]],
        frontoffset        = 0,
        fronttexture       = [[splashbase]],
        length             = [[16 r16]],
        sidetexture        = [[splashside]],
        size               = [[8 r4]],
        sizegrowth         = 1,
        ttl                = 24,
      },
    },
  },

}

