-- he_small

return {
  ["he_small"] = {
    usedefaultexplosions = false,
    dust = {
      class              = [[CBitmapMuzzleFlame]],
      count              = 8,
      ground             = true,
      properties = {
        colormap           = [[0.5 0.4 0.3 1  0.05 0.04 0.03 0.1]],
        dir                = [[-0.1 r0.2, 1, -0.1 r0.2]],
        frontoffset        = 0,
        fronttexture       = [[splashbase]],
        length             = [[8 r8]],
        sidetexture        = [[splashside]],
        size               = [[4 r2]],
        sizegrowth         = 1,
        ttl                = 12,
      },
    },
    groundflash = {
      circlealpha        = 0,
      circlegrowth       = 10,
      flashalpha         = 1,
      flashsize          = 16,
      ttl                = 8,
      color = {
        [1]  = 1,
        [2]  = 0.75,
        [3]  = 0.5,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.75,
        alwaysvisible      = false,
        colormap           = [[0.5 0.5 0.5 1  0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 8,
        particlelife       = 12,
        particlelifespread = 4,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[2 r2]],
        sizemod            = 0.5,
        texture            = [[smokesmall]],
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.125,
        color              = [[1,1,1]],
        expansionspeed     = 2,
        ttl                = 8,
      },
    },
    water = {
      class              = [[CBitmapMuzzleFlame]],
      count              = 8,
      water              = true,
      properties = {
        colormap           = [[0.45 0.45 0.5 0.5  0.045 0.045 0.05 0.05]],
        dir                = [[-0.1 r0.2, 1, -0.1 r0.2]],
        frontoffset        = 0,
        fronttexture       = [[splashbase]],
        length             = [[8 r8]],
        sidetexture        = [[splashside]],
        size               = [[4 r2]],
        sizegrowth         = 1,
        ttl                = 12,
      },
    },
  },

}

